name: Build Android App
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-11-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install kivy
          pip install cython
          
      - name: Verify project structure
        run: |
          echo "Checking project structure..."
          ls -la
          echo "Flags directory:"
          ls -la Flags/ || echo "Flags directory not found"
          echo "Reso directory:"
          ls -la Reso/ || echo "Reso directory not found"
          echo "Main files:"
          ls -la *.py *.kv *.txt *.png *.jpeg || echo "Some files not found"
          
      - name: Create buildozer.spec
        run: |
          cat > buildozer.spec << 'EOF'
          [app]
          title = Mon App
          package.name = monapp
          package.domain = org.example
          source.dir = .
          source.include_exts = py,png,jpg,jpeg,kv,atlas,txt
          source.include_patterns = Flags/*,Reso/*,*.png,*.jpeg,*.txt,*.kv
          version = 0.1
          requirements = python3,kivy
          
          [buildozer]
          log_level = 2
          warn_on_root = 1
          
          [app:android]
          arch = arm64-v8a
          api = 34
          minapi = 21
          sdk = 34
          ndk = 25c
          gradle_dependencies = 
          
          [app:android.permissions]
          android.permissions = INTERNET,ACCESS_NETWORK_STATE
          EOF
          
      - name: Build with Buildozer
        run: |
          buildozer android debug
          
      - name: Find APK file
        id: find_apk
        run: |
          APK_PATH=$(find . -name "*.apk" -type f | head -1)
          echo "APK found at: $APK_PATH"
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-package
          path: ${{ steps.find_apk.outputs.apk_path }}
          retention-days: 30
          
      - name: Upload to Release (if tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.find_apk.outputs.apk_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
